### ISSUE TITLE
"can't pickle lxml error" when loading this remote catalog?

### ISSUE THREAD

**Issue by rsignell-usgs** [eWaterCycle/jupyterlab_thredds#16]
I installed jupyterlab_thredds, and when I tried to search this thredds catalog:
http://geoport.whoi.edu/thredds/gom_bathy.xml
I got this "can't pickle lxml error" (see below)  

Is there something else I need to install or configure?

```
Crawling: http://geoport.whoi.edu/thredds/gom_bathy.xml
[E 08:32:25.975 LabApp] Uncaught exception GET /thredds?catalog_url=http%3A%2F%2Fgeoport.whoi.edu%2Fthredds%2Fgom_bathy.xml&1526905944190 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/thredds?catalog_url=http%3A%2F%2Fgeoport.whoi.edu%2Fthredds%2Fgom_bathy.xml&1526905944190', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\rsignell\miniconda3\envs\widgets\lib\site-packages\tornado\web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\Users\rsignell\miniconda3\envs\widgets\lib\site-packages\jupyterlab_thredds\__init__.py", line 56, in get
        crawl = Crawl(catalog_url, workers=c.workers)
      File "C:\Users\rsignell\miniconda3\envs\widgets\lib\site-packages\thredds_crawler\crawl.py", line 120, in __init__
        datasets = [j.get() for j in jobs]
      File "C:\Users\rsignell\miniconda3\envs\widgets\lib\site-packages\thredds_crawler\crawl.py", line 120, in <listcomp>
        datasets = [j.get() for j in jobs]
      File "C:\Users\rsignell\miniconda3\envs\widgets\lib\multiprocessing\pool.py", line 644, in get
        raise self._value
    multiprocessing.pool.MaybeEncodingError: Error sending result: '<LeafDataset id: bathy/gom15, name: USGS Gulf of Maine DEM (15 arc sec), services: ['OPENDAP', 'WCS', 'NetcdfSubset', 'WMS', 'HTTPServer', 'NCML', 'UDDC', 'ISO']>'. Reason: 'TypeError("can't pickle lxml.etree._Element objects",)'
[W 08:32:25.982 LabApp] Unhandled error
```

**Comment by rsignell-usgs** [comment]
Turns out I just needed to upgrade my `thredds_crawler`:
```
The following NEW packages will be INSTALLED:

    thredds_crawler: 1.5.4-py_1 conda-forge
```
![2018-05-21_10-25-59](https://user-images.githubusercontent.com/1872600/40312654-735df4ee-5ce1-11e8-87f1-2177ed7c13a7.png)
